"""Country name / demonym / ISO-3166-1 alpha-2 lookup used to resolve the
free-text `nationality` and `destination` fields on TripRequest into the
country codes the passport-index dataset (see integrations/visa.py) is keyed
by.

NAMES_BY_ISO2, NAME_ALIASES, DEMONYMS and REGION_BY_ISO2 below are generated
from the mledoze/countries dataset (https://github.com/mledoze/countries,
ODbL licensed) — common name, official name, alternate spellings, English
demonyms and continent region for all 250 ISO-3166 entries. Regenerate by
re-running the generation steps in this file's git history if the upstream
dataset changes.
"""

# A modest, non-exhaustive set of major destination cities, for when a user
# types just a city with no country (e.g. "Istanbul" rather than "Istanbul,
# Türkiye"). Country-name matching in resolve_country() already handles the
# common "City, Country" form; this is a fallback for city-only input.
CITY_HINTS = {
    "istanbul": "TR",
    "ankara": "TR",
    "antalya": "TR",
    "cairo": "EG",
    "nairobi": "KE",
    "mombasa": "KE",
    "zanzibar": "TZ",
    "dar es salaam": "TZ",
    "arusha": "TZ",
    "kigali": "RW",
    "kampala": "UG",
    "addis ababa": "ET",
    "lagos": "NG",
    "abuja": "NG",
    "accra": "GH",
    "casablanca": "MA",
    "marrakech": "MA",
    "tunis": "TN",
    "johannesburg": "ZA",
    "cape town": "ZA",
    "dubai": "AE",
    "abu dhabi": "AE",
    "doha": "QA",
    "riyadh": "SA",
    "jeddah": "SA",
    "mecca": "SA",
    "tel aviv": "IL",
    "jerusalem": "IL",
    "amman": "JO",
    "beirut": "LB",
    "mumbai": "IN",
    "delhi": "IN",
    "new delhi": "IN",
    "bangalore": "IN",
    "goa": "IN",
    "colombo": "LK",
    "dhaka": "BD",
    "kathmandu": "NP",
    "bangkok": "TH",
    "phuket": "TH",
    "chiang mai": "TH",
    "hanoi": "VN",
    "ho chi minh city": "VN",
    "saigon": "VN",
    "singapore": "SG",
    "kuala lumpur": "MY",
    "bali": "ID",
    "jakarta": "ID",
    "manila": "PH",
    "seoul": "KR",
    "tokyo": "JP",
    "osaka": "JP",
    "beijing": "CN",
    "shanghai": "CN",
    "hong kong": "HK",
    "london": "GB",
    "manchester": "GB",
    "edinburgh": "GB",
    "paris": "FR",
    "nice": "FR",
    "rome": "IT",
    "milan": "IT",
    "venice": "IT",
    "florence": "IT",
    "barcelona": "ES",
    "madrid": "ES",
    "lisbon": "PT",
    "amsterdam": "NL",
    "berlin": "DE",
    "munich": "DE",
    "vienna": "AT",
    "zurich": "CH",
    "geneva": "CH",
    "athens": "GR",
    "santorini": "GR",
    "mykonos": "GR",
    "prague": "CZ",
    "budapest": "HU",
    "warsaw": "PL",
    "stockholm": "SE",
    "oslo": "NO",
    "copenhagen": "DK",
    "reykjavik": "IS",
    "moscow": "RU",
    "new york": "US",
    "new york city": "US",
    "los angeles": "US",
    "san francisco": "US",
    "miami": "US",
    "las vegas": "US",
    "chicago": "US",
    "toronto": "CA",
    "vancouver": "CA",
    "montreal": "CA",
    "mexico city": "MX",
    "cancun": "MX",
    "rio de janeiro": "BR",
    "sao paulo": "BR",
    "buenos aires": "AR",
    "lima": "PE",
    "santiago": "CL",
    "bogota": "CO",
    "sydney": "AU",
    "melbourne": "AU",
    "auckland": "NZ",
}


def _normalize(text: str) -> str:
    return (text or "").strip().casefold()


def resolve_country(text: str) -> str | None:
    """Best-effort free-text -> ISO-3166 alpha-2 resolution for a
    destination string like "Istanbul, Türkiye" or "Nairobi". Tries, in
    order: an exact alias match on each comma-separated segment (handles
    "City, Country"), a substring scan against known country names/aliases
    (longest match wins, to prefer "South Africa" over "Africa"-shaped
    partial matches), then the CITY_HINTS table. Returns None if nothing
    matches, so callers can fall back to illustrative demo data.
    """
    normalized = _normalize(text)
    if not normalized:
        return None

    for segment in reversed(normalized.split(",")):
        segment = segment.strip()
        if segment in NAME_ALIASES:
            return NAME_ALIASES[segment]

    match = None
    for alias in sorted(NAME_ALIASES, key=len, reverse=True):
        if alias in normalized:
            match = NAME_ALIASES[alias]
            break
    if match:
        return match

    for city, code in CITY_HINTS.items():
        if city in normalized:
            return code

    return None


def resolve_nationality(text: str) -> str | None:
    """Best-effort free-text -> ISO-3166 alpha-2 resolution for a
    nationality string like "Tanzanian" (demonym) or "Tanzania" (country
    name, in case a user types it that way). Returns None if nothing
    matches.
    """
    normalized = _normalize(text)
    if not normalized:
        return None

    if normalized in DEMONYMS:
        return DEMONYMS[normalized]

    for demonym in sorted(DEMONYMS, key=len, reverse=True):
        if demonym in normalized:
            return DEMONYMS[demonym]

    return resolve_country(text)

NAMES_BY_ISO2 = {
    'AD': 'Andorra',
    'AE': 'United Arab Emirates',
    'AF': 'Afghanistan',
    'AG': 'Antigua and Barbuda',
    'AI': 'Anguilla',
    'AL': 'Albania',
    'AM': 'Armenia',
    'AO': 'Angola',
    'AQ': 'Antarctica',
    'AR': 'Argentina',
    'AS': 'American Samoa',
    'AT': 'Austria',
    'AU': 'Australia',
    'AW': 'Aruba',
    'AX': 'Åland Islands',
    'AZ': 'Azerbaijan',
    'BA': 'Bosnia and Herzegovina',
    'BB': 'Barbados',
    'BD': 'Bangladesh',
    'BE': 'Belgium',
    'BF': 'Burkina Faso',
    'BG': 'Bulgaria',
    'BH': 'Bahrain',
    'BI': 'Burundi',
    'BJ': 'Benin',
    'BL': 'Saint Barthélemy',
    'BM': 'Bermuda',
    'BN': 'Brunei',
    'BO': 'Bolivia',
    'BQ': 'Caribbean Netherlands',
    'BR': 'Brazil',
    'BS': 'Bahamas',
    'BT': 'Bhutan',
    'BV': 'Bouvet Island',
    'BW': 'Botswana',
    'BY': 'Belarus',
    'BZ': 'Belize',
    'CA': 'Canada',
    'CC': 'Cocos (Keeling) Islands',
    'CD': 'DR Congo',
    'CF': 'Central African Republic',
    'CG': 'Congo',
    'CH': 'Switzerland',
    'CI': 'Ivory Coast',
    'CK': 'Cook Islands',
    'CL': 'Chile',
    'CM': 'Cameroon',
    'CN': 'China',
    'CO': 'Colombia',
    'CR': 'Costa Rica',
    'CU': 'Cuba',
    'CV': 'Cape Verde',
    'CW': 'Curaçao',
    'CX': 'Christmas Island',
    'CY': 'Cyprus',
    'CZ': 'Czechia',
    'DE': 'Germany',
    'DJ': 'Djibouti',
    'DK': 'Denmark',
    'DM': 'Dominica',
    'DO': 'Dominican Republic',
    'DZ': 'Algeria',
    'EC': 'Ecuador',
    'EE': 'Estonia',
    'EG': 'Egypt',
    'EH': 'Western Sahara',
    'ER': 'Eritrea',
    'ES': 'Spain',
    'ET': 'Ethiopia',
    'FI': 'Finland',
    'FJ': 'Fiji',
    'FK': 'Falkland Islands',
    'FM': 'Micronesia',
    'FO': 'Faroe Islands',
    'FR': 'France',
    'GA': 'Gabon',
    'GB': 'United Kingdom',
    'GD': 'Grenada',
    'GE': 'Georgia',
    'GF': 'French Guiana',
    'GG': 'Guernsey',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GL': 'Greenland',
    'GM': 'Gambia',
    'GN': 'Guinea',
    'GP': 'Guadeloupe',
    'GQ': 'Equatorial Guinea',
    'GR': 'Greece',
    'GS': 'South Georgia',
    'GT': 'Guatemala',
    'GU': 'Guam',
    'GW': 'Guinea-Bissau',
    'GY': 'Guyana',
    'HK': 'Hong Kong',
    'HM': 'Heard Island and McDonald Islands',
    'HN': 'Honduras',
    'HR': 'Croatia',
    'HT': 'Haiti',
    'HU': 'Hungary',
    'ID': 'Indonesia',
    'IE': 'Ireland',
    'IL': 'Israel',
    'IM': 'Isle of Man',
    'IN': 'India',
    'IO': 'British Indian Ocean Territory',
    'IQ': 'Iraq',
    'IR': 'Iran',
    'IS': 'Iceland',
    'IT': 'Italy',
    'JE': 'Jersey',
    'JM': 'Jamaica',
    'JO': 'Jordan',
    'JP': 'Japan',
    'KE': 'Kenya',
    'KG': 'Kyrgyzstan',
    'KH': 'Cambodia',
    'KI': 'Kiribati',
    'KM': 'Comoros',
    'KN': 'Saint Kitts and Nevis',
    'KP': 'North Korea',
    'KR': 'South Korea',
    'KW': 'Kuwait',
    'KY': 'Cayman Islands',
    'KZ': 'Kazakhstan',
    'LA': 'Laos',
    'LB': 'Lebanon',
    'LC': 'Saint Lucia',
    'LI': 'Liechtenstein',
    'LK': 'Sri Lanka',
    'LR': 'Liberia',
    'LS': 'Lesotho',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'LV': 'Latvia',
    'LY': 'Libya',
    'MA': 'Morocco',
    'MC': 'Monaco',
    'MD': 'Moldova',
    'ME': 'Montenegro',
    'MF': 'Saint Martin',
    'MG': 'Madagascar',
    'MH': 'Marshall Islands',
    'MK': 'North Macedonia',
    'ML': 'Mali',
    'MM': 'Myanmar',
    'MN': 'Mongolia',
    'MO': 'Macau',
    'MP': 'Northern Mariana Islands',
    'MQ': 'Martinique',
    'MR': 'Mauritania',
    'MS': 'Montserrat',
    'MT': 'Malta',
    'MU': 'Mauritius',
    'MV': 'Maldives',
    'MW': 'Malawi',
    'MX': 'Mexico',
    'MY': 'Malaysia',
    'MZ': 'Mozambique',
    'NA': 'Namibia',
    'NC': 'New Caledonia',
    'NE': 'Niger',
    'NF': 'Norfolk Island',
    'NG': 'Nigeria',
    'NI': 'Nicaragua',
    'NL': 'Netherlands',
    'NO': 'Norway',
    'NP': 'Nepal',
    'NR': 'Nauru',
    'NU': 'Niue',
    'NZ': 'New Zealand',
    'OM': 'Oman',
    'PA': 'Panama',
    'PE': 'Peru',
    'PF': 'French Polynesia',
    'PG': 'Papua New Guinea',
    'PH': 'Philippines',
    'PK': 'Pakistan',
    'PL': 'Poland',
    'PM': 'Saint Pierre and Miquelon',
    'PN': 'Pitcairn Islands',
    'PR': 'Puerto Rico',
    'PS': 'Palestine',
    'PT': 'Portugal',
    'PW': 'Palau',
    'PY': 'Paraguay',
    'QA': 'Qatar',
    'RE': 'Réunion',
    'RO': 'Romania',
    'RS': 'Serbia',
    'RU': 'Russia',
    'RW': 'Rwanda',
    'SA': 'Saudi Arabia',
    'SB': 'Solomon Islands',
    'SC': 'Seychelles',
    'SD': 'Sudan',
    'SE': 'Sweden',
    'SG': 'Singapore',
    'SH': 'Saint Helena, Ascension and Tristan da Cunha',
    'SI': 'Slovenia',
    'SJ': 'Svalbard and Jan Mayen',
    'SK': 'Slovakia',
    'SL': 'Sierra Leone',
    'SM': 'San Marino',
    'SN': 'Senegal',
    'SO': 'Somalia',
    'SR': 'Suriname',
    'SS': 'South Sudan',
    'ST': 'São Tomé and Príncipe',
    'SV': 'El Salvador',
    'SX': 'Sint Maarten',
    'SY': 'Syria',
    'SZ': 'Eswatini',
    'TC': 'Turks and Caicos Islands',
    'TD': 'Chad',
    'TF': 'French Southern and Antarctic Lands',
    'TG': 'Togo',
    'TH': 'Thailand',
    'TJ': 'Tajikistan',
    'TK': 'Tokelau',
    'TL': 'Timor-Leste',
    'TM': 'Turkmenistan',
    'TN': 'Tunisia',
    'TO': 'Tonga',
    'TR': 'Türkiye',
    'TT': 'Trinidad and Tobago',
    'TV': 'Tuvalu',
    'TW': 'Taiwan',
    'TZ': 'Tanzania',
    'UA': 'Ukraine',
    'UG': 'Uganda',
    'UM': 'United States Minor Outlying Islands',
    'US': 'United States',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VA': 'Vatican City',
    'VC': 'Saint Vincent and the Grenadines',
    'VE': 'Venezuela',
    'VG': 'British Virgin Islands',
    'VI': 'United States Virgin Islands',
    'VN': 'Vietnam',
    'VU': 'Vanuatu',
    'WF': 'Wallis and Futuna',
    'WS': 'Samoa',
    'XK': 'Kosovo',
    'YE': 'Yemen',
    'YT': 'Mayotte',
    'ZA': 'South Africa',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe',
}

NAME_ALIASES = {
    'aaland': 'AX',
    'afghanistan': 'AF',
    'afġānistān': 'AF',
    'ahvenanmaa': 'AX',
    'al-ittiḥād al-qumurī': 'KM',
    'al-jumhūriyyah al-yamaniyyah': 'YE',
    'al-jumhūriyyah al-ʾislāmiyyah al-mūrītāniyyah': 'MR',
    'al-jumhūriyyah at-tūnisiyyah': 'TN',
    'al-jumhūrīyah al-libnānīyah': 'LB',
    'al-jumhūrīyah al-ʻarabīyah as-sūrīyah': 'SY',
    'al-mamlakah al-maġribiyah': 'MA',
    'al-mamlakah al-urdunīyah al-hāshimīyah': 'JO',
    'al-mamlakah al-‘arabiyyah as-su‘ūdiyyah': 'SA',
    'aland': 'AX',
    'albania': 'AL',
    'algeria': 'DZ',
    'algérie': 'DZ',
    'amelika sāmoa': 'AS',
    'american samoa': 'AS',
    'amerika sāmoa': 'AS',
    'andorra': 'AD',
    'angola': 'AO',
    'anguilla': 'AI',
    'antarctica': 'AQ',
    'antigua and barbuda': 'AG',
    'aolepān aorōkin m̧ajeļ': 'MH',
    'aotearoa': 'NZ',
    'arab republic of egypt': 'EG',
    'argentina': 'AR',
    'argentine republic': 'AR',
    'armenia': 'AM',
    'aruba': 'AW',
    'australia': 'AU',
    'austria': 'AT',
    'azerbaijan': 'AZ',
    'azərbaycan respublikası': 'AZ',
    'aṣ-ṣūmāl': 'SO',
    'bahamas': 'BS',
    'bahrain': 'BH',
    'bailiwick of guernsey': 'GG',
    'bailiwick of jersey': 'JE',
    'bailliage de guernesey': 'GG',
    'bailliage de jersey': 'JE',
    'bailliage dé jèrri': 'JE',
    'bangladesh': 'BD',
    'barbados': 'BB',
    'belarus': 'BY',
    'belgie': 'BE',
    'belgien': 'BE',
    'belgique': 'BE',
    'belgium': 'BE',
    'belgië': 'BE',
    'belize': 'BZ',
    'beluu er a belau': 'PW',
    'benin': 'BJ',
    'bermuda': 'BM',
    'bes islands': 'BQ',
    'bharat ganrajya': 'IN',
    'bhutan': 'BT',
    'bhārat': 'IN',
    'bielaruś': 'BY',
    'bolivarian republic of venezuela': 'VE',
    'bolivia': 'BO',
    'bolivia, plurinational state of': 'BO',
    'bonaire sint eustatius and saba': 'BQ',
    'bonaire, sint eustatius and saba': 'BQ',
    'bosnia and herzegovina': 'BA',
    'bosnia-herzegovina': 'BA',
    'botswana': 'BW',
    'bouvet island': 'BV',
    'bouvet-øya': 'BV',
    'bouvetøya': 'BV',
    'brasil': 'BR',
    'brazil': 'BR',
    'british indian ocean territory': 'IO',
    'british virgin islands': 'VG',
    'brunei': 'BN',
    'brunei darussalam': 'BN',
    'bulgaria': 'BG',
    'buliwya': 'BO',
    'buliwya mamallaqta': 'BO',
    'bundesrepublik deutschland': 'DE',
    'burkina faso': 'BF',
    'burma': 'MM',
    'burundi': 'BI',
    'cambodia': 'KH',
    'cameroon': 'CM',
    'canada': 'CA',
    'cape verde': 'CV',
    'caribbean netherlands': 'BQ',
    'cayman islands': 'KY',
    'central african republic': 'CF',
    'chad': 'TD',
    'chile': 'CL',
    'china': 'CN',
    'chinese taipei': 'TW',
    'chosŏn minjujuŭi inmin konghwaguk': 'KP',
    'christmas island': 'CX',
    'co-operative republic of guyana': 'GY',
    'cocos (keeling) islands': 'CC',
    'cocos islands': 'CC',
    'collectivity of saint barthélemy': 'BL',
    'collectivity of saint martin': 'MF',
    'collectivité de saint-barthélemy': 'BL',
    'collectivité de saint-martin': 'MF',
    'collectivité territoriale de saint-pierre-et-miquelon': 'PM',
    'colombia': 'CO',
    'commonwealth of australia': 'AU',
    'commonwealth of dominica': 'DM',
    'commonwealth of puerto rico': 'PR',
    'commonwealth of the bahamas': 'BS',
    'commonwealth of the northern mariana islands': 'MP',
    'comoros': 'KM',
    'congo': 'CG',
    'congo, the democratic republic of the': 'CD',
    'congo-brazzaville': 'CG',
    'congo-kinshasa': 'CD',
    'cook islands': 'CK',
    'costa rica': 'CR',
    "cote d'ivoire": 'CI',
    'country of curaçao': 'CW',
    'crna gora': 'ME',
    'croatia': 'HR',
    'cuba': 'CU',
    'curacao': 'CW',
    'curaçao': 'CW',
    'cyprus': 'CY',
    'czech republic': 'CZ',
    'czechia': 'CZ',
    "côte d'ivoire": 'CI',
    'cộng hòa xã hội chủ nghĩa việt nam': 'VN',
    'danmark': 'DK',
    'dawlat al-kuwait': 'KW',
    'dawlat filasṭin': 'PS',
    'dawlat iritriyá': 'ER',
    'dawlat libya': 'LY',
    'dawlat qaṭar': 'QA',
    "democratic people's republic of korea": 'KP',
    'democratic republic of congo': 'CD',
    'democratic republic of são tomé and príncipe': 'ST',
    'democratic republic of the congo': 'CD',
    'democratic republic of timor-leste': 'TL',
    'democratic socialist republic of sri lanka': 'LK',
    'denmark': 'DK',
    'department of mayotte': 'YT',
    'dhivehi raajjeyge jumhooriyya': 'MV',
    'djibouti': 'DJ',
    'dominica': 'DM',
    'dominican republic': 'DO',
    'dominique': 'DM',
    'dprk': 'KP',
    'dr congo': 'CD',
    'drc': 'CD',
    'dzayer': 'DZ',
    'département de mayotte': 'YT',
    'east timor': 'TL',
    'ecuador': 'EC',
    'eesti': 'EE',
    'eesti vabariik': 'EE',
    'egypt': 'EG',
    'el salvador': 'SV',
    'ellan vannin': 'IM',
    'elláda': 'GR',
    'emirates': 'AE',
    'equatorial guinea': 'GQ',
    'eritrea': 'ER',
    'estado libre asociado de puerto rico': 'PR',
    'estado plurinacional de bolivia': 'BO',
    'estados unidos mexicanos': 'MX',
    'estonia': 'EE',
    'eswatini': 'SZ',
    'ethiopia': 'ET',
    'faeroe islands': 'FO',
    'falkland islands': 'FK',
    'falkland islands (malvinas)': 'FK',
    'faroe islands': 'FO',
    'federal democratic republic of ethiopia': 'ET',
    'federal democratic republic of nepal': 'NP',
    'federal republic of germany': 'DE',
    'federal republic of nigeria': 'NG',
    'federal republic of somalia': 'SO',
    'federated states of micronesia': 'FM',
    'federation of saint christopher and nevis': 'KN',
    'federative republic of brazil': 'BR',
    'fiji': 'FJ',
    'fijī gaṇarājya': 'FJ',
    'finland': 'FI',
    'france': 'FR',
    'french guiana': 'GF',
    'french polynesia': 'PF',
    'french republic': 'FR',
    'french southern and antarctic lands': 'TF',
    'french southern territories': 'TF',
    'færøerne': 'FO',
    'føroyar': 'FO',
    'fürstentum liechtenstein': 'LI',
    'gabon': 'GA',
    'gabonese republic': 'GA',
    'gabuuti': 'DJ',
    'gabuutih ummuuno': 'DJ',
    'gambia': 'GM',
    'georgia': 'GE',
    'germany': 'DE',
    'ghana': 'GH',
    'gibraltar': 'GI',
    'grand duchy of luxembourg': 'LU',
    'grand-duché de luxembourg': 'LU',
    'great britain': 'GB',
    'greece': 'GR',
    'greenland': 'GL',
    'grenada': 'GD',
    'groussherzogtum lëtzebuerg': 'LU',
    'großherzogtum luxemburg': 'LU',
    'grønland': 'GL',
    'guadeloupe': 'GP',
    'guam': 'GU',
    'guatemala': 'GT',
    'guernsey': 'GG',
    'guiana': 'GF',
    'guinea': 'GN',
    'guinea-bissau': 'GW',
    'guyana': 'GY',
    'guyane': 'GF',
    'guåhån': 'GU',
    'gwadloup': 'GP',
    'gônôprôjatôntri bangladesh': 'BD',
    'haiti': 'HT',
    'hashemite kingdom of jordan': 'JO',
    'hayastan': 'AM',
    'heard island and mcdonald islands': 'HM',
    'hellenic republic': 'GR',
    'holland': 'NL',
    'holy see (vatican city state)': 'VA',
    'honduras': 'HN',
    'hong kong': 'HK',
    "hong kong special administrative region of the people's republic of china": 'HK',
    'hrvatska': 'HR',
    'hungary': 'HU',
    'iceland': 'IS',
    'ilaṅkai': 'LK',
    'independen stet bilong papua niugini': 'PG',
    'independent and sovereign republic of kiribati': 'KI',
    'independent state of papua new guinea': 'PG',
    'independent state of samoa': 'WS',
    'india': 'IN',
    'indonesia': 'ID',
    'iran': 'IR',
    'iran, islamic republic of': 'IR',
    'iraq': 'IQ',
    'ireland': 'IE',
    'iritriyā': 'ER',
    'islamic republic of afghanistan': 'AF',
    'islamic republic of iran': 'IR',
    'islamic republic of mauritania': 'MR',
    'islamic republic of pakistan': 'PK',
    'island': 'IS',
    'islas malvinas': 'FK',
    'isle of man': 'IM',
    "islāmī jumhūriya'eh pākistān": 'PK',
    'israel': 'IL',
    'italian republic': 'IT',
    'italy': 'IT',
    'ivory coast': 'CI',
    'jabuuti': 'DJ',
    'jamaica': 'JM',
    'jamhuri ya kenya': 'KE',
    'jamhuri ya muungano wa tanzania': 'TZ',
    'jamhuri ya uganda': 'UG',
    'jamhuuriyadda federaalka soomaaliya': 'SO',
    'jamhuuriyadda jabuuti': 'DJ',
    'japan': 'JP',
    'jersey': 'JE',
    'jomhuri-ye eslāmi-ye irān': 'IR',
    'jordan': 'JO',
    'jumhūriyyat al-‘irāq': 'IQ',
    'jumhūriyyat aṣ-ṣūmāl al-fiderāliyya': 'SO',
    'jumhūrīyat as-sūdān': 'SD',
    'kazakhstan': 'KZ',
    'keeling islands': 'CC',
    'kenya': 'KE',
    'kingdom of bahrain': 'BH',
    'kingdom of belgium': 'BE',
    'kingdom of bhutan': 'BT',
    'kingdom of cambodia': 'KH',
    'kingdom of denmark': 'DK',
    'kingdom of eswatini': 'SZ',
    'kingdom of lesotho': 'LS',
    'kingdom of morocco': 'MA',
    'kingdom of norway': 'NO',
    'kingdom of saudi arabia': 'SA',
    'kingdom of spain': 'ES',
    'kingdom of sweden': 'SE',
    'kingdom of thailand': 'TH',
    'kingdom of the netherlands': 'NL',
    'kingdom of tonga': 'TO',
    'kiribati': 'KI',
    'kongeriget danmark': 'DK',
    'kongeriket noreg': 'NO',
    'kongeriket norge': 'NO',
    'koninkrijk belgië': 'BE',
    'konungariket sverige': 'SE',
    "korea, democratic people's republic of": 'KP',
    'korea, republic of': 'KR',
    'kosovo': 'XK',
    'kuwait': 'KW',
    'kyrgyz republic': 'KG',
    'kyrgyz respublikasy': 'KG',
    'kyrgyzstan': 'KG',
    'kòrsou': 'CW',
    'königreich belgien': 'BE',
    'kýpros': 'CY',
    'kıbrıs': 'CY',
    'kıbrıs cumhuriyeti': 'CY',
    "kūki 'āirani": 'CK',
    'land curaçao': 'CW',
    'lao': 'LA',
    "lao people's democratic republic": 'LA',
    'laos': 'LA',
    'latvia': 'LV',
    'latvijas republika': 'LV',
    'lebanese republic': 'LB',
    'lebanon': 'LB',
    'lefatshe la botswana': 'BW',
    'lesotho': 'LS',
    'liberia': 'LR',
    'libya': 'LY',
    'liechtenstein': 'LI',
    'lietuvos respublika': 'LT',
    'lithuania': 'LT',
    'loktāntrik ganatantra nepāl': 'NP',
    'luxembourg': 'LU',
    'lýðveldið ísland': 'IS',
    'macao': 'MO',
    "macao special administrative region of the people's republic of china": 'MO',
    'macau': 'MO',
    'macedonia': 'MK',
    'macedonia, the former yugoslav republic of': 'MK',
    'madagascar': 'MG',
    'malawi': 'MW',
    'malaysia': 'MY',
    'maldive islands': 'MV',
    'maldives': 'MV',
    'mali': 'ML',
    'malo saʻoloto tutoʻatasi o sāmoa': 'WS',
    'malta': 'MT',
    'mamlakat al-baḥrayn': 'BH',
    'mann': 'IM',
    'mannin': 'IM',
    'marshall islands': 'MH',
    'martinique': 'MQ',
    'matanitu ko viti': 'FJ',
    'mauritania': 'MR',
    'mauritius': 'MU',
    'mayotte': 'YT',
    "medīnat yisrā'el": 'IL',
    'mexicanos': 'MX',
    'mexico': 'MX',
    'micronesia': 'FM',
    'micronesia, federated states of': 'FM',
    'moldova': 'MD',
    'moldova, republic of': 'MD',
    'monaco': 'MC',
    'mongolia': 'MN',
    'montenegro': 'ME',
    'montserrat': 'MS',
    'morocco': 'MA',
    'most serene republic of san marino': 'SM',
    'mozambique': 'MZ',
    'muso oa lesotho': 'LS',
    'myanmar': 'MM',
    'namibia': 'NA',
    'namibië': 'NA',
    'naoero': 'NR',
    'nation of brunei': 'BN',
    'nation of brunei, abode of peace': 'BN',
    'nauru': 'NR',
    'naíjíríà': 'NG',
    'nederland': 'NL',
    'nepal': 'NP',
    'netherlands': 'NL',
    'new caledonia': 'NC',
    'new zealand': 'NZ',
    'ngwane': 'SZ',
    'nicaragua': 'NI',
    'niger': 'NE',
    'nigeria': 'NG',
    'nihon': 'JP',
    'nijar': 'NE',
    'nijeriya': 'NG',
    'nippon': 'JP',
    'niue': 'NU',
    'noreg': 'NO',
    'norfolk island': 'NF',
    'norge': 'NO',
    'north korea': 'KP',
    'north macedonia': 'MK',
    'northern mariana islands': 'MP',
    'norway': 'NO',
    'oesterreich': 'AT',
    'oman': 'OM',
    'oriental republic of uruguay': 'UY',
    'osterreich': 'AT',
    'o‘zbekiston respublikasi': 'UZ',
    'pais kòrsou': 'CW',
    'pakistan': 'PK',
    'palau': 'PW',
    'palestine': 'PS',
    'palestine, state of': 'PS',
    'panama': 'PA',
    'papua new guinea': 'PG',
    'paraguay': 'PY',
    "people's democratic republic of algeria": 'DZ',
    "people's republic of bangladesh": 'BD',
    "people's republic of china": 'CN',
    'peru': 'PE',
    'philippines': 'PH',
    'pitcairn': 'PN',
    'pitcairn group of islands': 'PN',
    'pitcairn henderson ducie and oeno islands': 'PN',
    'pitcairn islands': 'PN',
    'pleasant island': 'NR',
    'plurinational state of bolivia': 'BO',
    'poblacht na héireann': 'IE',
    'poland': 'PL',
    'polynésie française': 'PF',
    'portugal': 'PT',
    'portuguesa': 'PT',
    'portuguese republic': 'PT',
    'prathet': 'TH',
    'principality of andorra': 'AD',
    'principality of liechtenstein': 'LI',
    'principality of monaco': 'MC',
    "principat d'andorra": 'AD',
    'principauté de monaco': 'MC',
    'puerto rico': 'PR',
    'pyidaunzu thanmăda myăma nainngandaw': 'MM',
    'pākistān': 'PK',
    'pōrīnetia farāni': 'PF',
    'qatar': 'QA',
    'qazaqstan': 'KZ',
    'qazaqstan respublïkası': 'KZ',
    'ratcha anachak thai': 'TH',
    'região administrativa especial de macau da república popular da china': 'MO',
    'reino de españa': 'ES',
    'repiblik ayiti': 'HT',
    'repiblik sesel': 'SC',
    "repoblikan'i madagasikara": 'MG',
    'repubblica di san marino': 'SM',
    'repubblica italiana': 'IT',
    "repubblika ta' malta": 'MT',
    'republic of albania': 'AL',
    'republic of angola': 'AO',
    'republic of armenia': 'AM',
    'republic of austria': 'AT',
    'republic of azerbaijan': 'AZ',
    'republic of belarus': 'BY',
    'republic of benin': 'BJ',
    'republic of botswana': 'BW',
    'republic of bulgaria': 'BG',
    'republic of burundi': 'BI',
    'republic of cabo verde': 'CV',
    'republic of cameroon': 'CM',
    'republic of chad': 'TD',
    'republic of chile': 'CL',
    'republic of china': 'TW',
    'republic of china (taiwan)': 'TW',
    'republic of colombia': 'CO',
    'republic of costa rica': 'CR',
    'republic of croatia': 'HR',
    'republic of cuba': 'CU',
    'republic of cyprus': 'CY',
    "republic of côte d'ivoire": 'CI',
    'republic of djibouti': 'DJ',
    'republic of ecuador': 'EC',
    'republic of el salvador': 'SV',
    'republic of equatorial guinea': 'GQ',
    'republic of estonia': 'EE',
    'republic of fiji': 'FJ',
    'republic of finland': 'FI',
    'republic of ghana': 'GH',
    'republic of guatemala': 'GT',
    'republic of guinea': 'GN',
    'republic of guinea-bissau': 'GW',
    'republic of haiti': 'HT',
    'republic of honduras': 'HN',
    'republic of iceland': 'IS',
    'republic of india': 'IN',
    'republic of indonesia': 'ID',
    'republic of iraq': 'IQ',
    'republic of ireland': 'IE',
    'republic of kazakhstan': 'KZ',
    'republic of kenya': 'KE',
    'republic of kiribati': 'KI',
    'republic of korea': 'KR',
    'republic of kosovo': 'XK',
    'republic of latvia': 'LV',
    'republic of liberia': 'LR',
    'republic of lithuania': 'LT',
    'republic of madagascar': 'MG',
    'republic of malawi': 'MW',
    'republic of mali': 'ML',
    'republic of malta': 'MT',
    'republic of mauritius': 'MU',
    'republic of moldova': 'MD',
    'republic of mozambique': 'MZ',
    'republic of namibia': 'NA',
    'republic of nauru': 'NR',
    'republic of nicaragua': 'NI',
    'republic of niger': 'NE',
    'republic of north macedonia': 'MK',
    'republic of palau': 'PW',
    'republic of panama': 'PA',
    'republic of paraguay': 'PY',
    'republic of peru': 'PE',
    'republic of poland': 'PL',
    'republic of rwanda': 'RW',
    'republic of san marino': 'SM',
    'republic of senegal': 'SN',
    'republic of serbia': 'RS',
    'republic of seychelles': 'SC',
    'republic of sierra leone': 'SL',
    'republic of singapore': 'SG',
    'republic of slovenia': 'SI',
    'republic of south africa': 'ZA',
    'republic of south sudan': 'SS',
    'republic of suriname': 'SR',
    'republic of tajikistan': 'TJ',
    'republic of the congo': 'CG',
    'republic of the gambia': 'GM',
    'republic of the maldives': 'MV',
    'republic of the marshall islands': 'MH',
    'republic of the philippines': 'PH',
    'republic of the sudan': 'SD',
    'republic of the union of myanmar': 'MM',
    'republic of trinidad and tobago': 'TT',
    'republic of tunisia': 'TN',
    'republic of turkey': 'TR',
    'republic of türkiye': 'TR',
    'republic of uganda': 'UG',
    'republic of uzbekistan': 'UZ',
    'republic of vanuatu': 'VU',
    'republic of yemen': 'YE',
    'republic of zambia': 'ZM',
    'republic of zimbabwe': 'ZW',
    'republica moldova': 'MD',
    'republiek suriname': 'SR',
    'republik indonesia': 'ID',
    'republik singapura': 'SG',
    'republika hrvatska': 'HR',
    'republika slovenija': 'SI',
    'republika srbija': 'RS',
    "republika y'uburundi": 'BI',
    'republiken finland': 'FI',
    "repubulika y'u rwanda": 'RW',
    'república argentina': 'AR',
    'república bolivariana de venezuela': 'VE',
    'república da guiné equatorial': 'GQ',
    'república da guiné-bissau': 'GW',
    'república de angola': 'AO',
    'república de cabo verde': 'CV',
    'república de chile': 'CL',
    'república de colombia': 'CO',
    'república de costa rica': 'CR',
    'república de cuba': 'CU',
    'república de el salvador': 'SV',
    'república de guinea ecuatorial': 'GQ',
    'república de honduras': 'HN',
    'república de moçambique': 'MZ',
    'república de nicaragua': 'NI',
    'república de panamá': 'PA',
    'república del ecuador': 'EC',
    'república del paraguay': 'PY',
    'república del perú': 'PE',
    'república democrática de são tomé e príncipe': 'ST',
    'república democrática de timor-leste': 'TL',
    'república federativa do brasil': 'BR',
    'república oriental del uruguay': 'UY',
    'república portuguesa': 'PT',
    'repúblika demokrátika timór-leste': 'TL',
    'repúblika ng pilipinas': 'PH',
    'respublika kazakhstan': 'KZ',
    'reunion': 'RE',
    'ribaberiki kiribati': 'KI',
    'ripablik blong vanuatu': 'VU',
    'ripublik naoero': 'NR',
    'romania': 'RO',
    'românia': 'RO',
    'roumania': 'RO',
    'royaume de belgique': 'BE',
    'rsa': 'ZA',
    'rumania': 'RO',
    'russia': 'RU',
    'russian federation': 'RU',
    'rwanda': 'RW',
    'rzeczpospolita polska': 'PL',
    'république centrafricaine': 'CF',
    "république d'haïti": 'HT',
    "république de côte d'ivoire": 'CI',
    'république de djibouti': 'DJ',
    'république de guinée': 'GN',
    'république de guinée équatoriale': 'GQ',
    'république de madagascar': 'MG',
    'république de maurice': 'MU',
    'république de vanuatu': 'VU',
    'république des seychelles': 'SC',
    'république du burundi': 'BI',
    'république du bénin': 'BJ',
    'république du cameroun': 'CM',
    'république du mali': 'ML',
    'république du rwanda': 'RW',
    'république du sénégal': 'SN',
    'république du tchad': 'TD',
    'république française': 'FR',
    'république gabonaise': 'GA',
    'république togolaise': 'TG',
    'réunion': 'RE',
    'réunion island': 'RE',
    'sahrawi arab democratic republic': 'EH',
    'saint barthélemy': 'BL',
    'saint helena': 'SH',
    'saint helena, ascension and tristan da cunha': 'SH',
    'saint kitts and nevis': 'KN',
    'saint lucia': 'LC',
    'saint martin': 'MF',
    'saint martin (french part)': 'MF',
    'saint pierre and miquelon': 'PM',
    'saint vincent and the grenadines': 'VC',
    'sakartvelo': 'GE',
    'salṭanat ʻumān': 'OM',
    'samoa': 'WS',
    'san marino': 'SM',
    'sankattan siha na islas mariånas': 'MP',
    'sao tome and principe': 'ST',
    'sarnam': 'SR',
    'sathalanalat paxathipatai paxaxon lao': 'LA',
    'saudi': 'SA',
    'saudi arabia': 'SA',
    'schweiz': 'CH',
    'senegal': 'SN',
    'serbia': 'RS',
    'seychelles': 'SC',
    'shqipnia': 'AL',
    'shqipëri': 'AL',
    'shqipëria': 'AL',
    'sierra leone': 'SL',
    'singapore': 'SG',
    'singapura': 'SG',
    'sint maarten': 'SX',
    'sint maarten (dutch part)': 'SX',
    'slovak republic': 'SK',
    'slovakia': 'SK',
    'slovenia': 'SI',
    'slovenská republika': 'SK',
    'socialist republic of vietnam': 'VN',
    'solomon islands': 'SB',
    'somalia': 'SO',
    'somers isles': 'BM',
    'south africa': 'ZA',
    'south georgia': 'GS',
    'south georgia and the south sandwich islands': 'GS',
    'south korea': 'KR',
    'south sudan': 'SS',
    'spain': 'ES',
    'sranangron': 'SR',
    'srbija': 'RS',
    'sri lanka': 'LK',
    'st. barthelemy': 'BL',
    'st. helena, ascension and tristan da cunha': 'SH',
    'state of eritrea': 'ER',
    'state of israel': 'IL',
    'state of kuwait': 'KW',
    'state of libya': 'LY',
    'state of palestine': 'PS',
    'state of qatar': 'QA',
    'stato della città del vaticano': 'VA',
    'sudan': 'SD',
    'suid-afrika': 'ZA',
    'suisse': 'CH',
    'sultanate of oman': 'OM',
    'suomen tasavalta': 'FI',
    'suomi': 'FI',
    'suriname': 'SR',
    'svalbard and jan mayen': 'SJ',
    'svalbard and jan mayen islands': 'SJ',
    'svalbard og jan mayen': 'SJ',
    'svizra': 'CH',
    'svizzera': 'CH',
    'swatini': 'SZ',
    'swaziland': 'SZ',
    'sweden': 'SE',
    'swiss confederation': 'CH',
    'switzerland': 'CH',
    'syria': 'SY',
    'syrian arab republic': 'SY',
    'são tomé and príncipe': 'ST',
    'sāmoa amelika': 'AS',
    'taiwan': 'TW',
    'tajikistan': 'TJ',
    'taneẓroft tutrimt': 'EH',
    'tanzania': 'TZ',
    'tanzania, united republic of': 'TZ',
    'tchad': 'TD',
    "teratri of norf'k ailen": 'NF',
    'territoire des îles wallis et futuna': 'WF',
    'territory of christmas island': 'CX',
    'territory of norfolk island': 'NF',
    'territory of the cocos (keeling) islands': 'CC',
    'territory of the french southern and antarctic lands': 'TF',
    'territory of the wallis and futuna islands': 'WF',
    'tetã paraguái': 'PY',
    'tetã volívia': 'BO',
    'thai': 'TH',
    'thailand': 'TH',
    'the abode of peace': 'BN',
    'the bermudas': 'BM',
    'the former yugoslav republic of macedonia': 'MK',
    'the islands of bermuda': 'BM',
    'the netherlands': 'NL',
    'timor': 'TL',
    'timor lorosae': 'TL',
    'timor-leste': 'TL',
    "timór lorosa'e": 'TL',
    'togo': 'TG',
    'togolese': 'TG',
    'togolese republic': 'TG',
    'tokelau': 'TK',
    'tonga': 'TO',
    'toçikiston': 'TJ',
    'trinidad and tobago': 'TT',
    'tunisia': 'TN',
    'tunisian republic': 'TN',
    'turkiye': 'TR',
    'turkmenistan': 'TM',
    'turks and caicos islands': 'TC',
    'tuvalu': 'TV',
    'táiwān': 'TW',
    'türkiye': 'TR',
    'türkiye cumhuriyeti': 'TR',
    'uae': 'AE',
    'udzima wa komori': 'KM',
    'uganda': 'UG',
    'ukraine': 'UA',
    'ukrayina': 'UA',
    'umbuso weswatini': 'SZ',
    'union des comores': 'KM',
    'union of the comoros': 'KM',
    'united arab emirates': 'AE',
    'united kingdom': 'GB',
    'united kingdom of great britain and northern ireland': 'GB',
    'united mexican states': 'MX',
    'united republic of tanzania': 'TZ',
    'united states': 'US',
    'united states minor outlying islands': 'UM',
    'united states of america': 'US',
    'united states virgin islands': 'VI',
    'uruguay': 'UY',
    'usa': 'US',
    'uzbekistan': 'UZ',
    'vanuatu': 'VU',
    'vatican': 'VA',
    'vatican city': 'VA',
    'vatican city state': 'VA',
    'venezuela': 'VE',
    'venezuela, bolivarian republic of': 'VE',
    'viet nam': 'VN',
    'vietnam': 'VN',
    'virgin islands': 'VG',
    'virgin islands of the united states': 'VI',
    'virgin islands, british': 'VG',
    'virgin islands, u.s.': 'VI',
    'viti': 'FJ',
    'wai‘tu kubuli': 'DM',
    'wallis and futuna': 'WF',
    'western sahara': 'EH',
    'weswatini': 'SZ',
    'wuliwya': 'BO',
    'wuliwya suyu': 'BO',
    'yemen': 'YE',
    'yemeni republic': 'YE',
    'zambia': 'ZM',
    'zhongguo': 'CN',
    'zhonghua': 'CN',
    'zhōngguó': 'CN',
    'zhōnghuá mínguó': 'TW',
    'zhōnghuá rénmín gònghéguó': 'CN',
    'zimbabwe': 'ZW',
    'åland islands': 'AX',
    'çumhuriyi toçikiston': 'TJ',
    'éire': 'IE',
    'česko': 'CZ',
    'česká republika': 'CZ',
    "ʁɛpublika de an'ɡɔla": 'AO',
    'ʾertrā': 'ER',
    'ʾītyōṗṗyā': 'ET',
    'ελληνική δημοκρατία': 'GR',
    'κυπριακή δημοκρατία': 'CY',
    'белоруссия': 'BY',
    'босна и херцеговина': 'BA',
    'казахстан': 'KZ',
    'киргизия': 'KG',
    'кыргыз республикасы': 'KG',
    'република българия': 'BG',
    'република косово': 'XK',
    'република северна македонија': 'MK',
    'република србија': 'RS',
    'республика белоруссия': 'BY',
    'республика казахстан': 'KZ',
    'российская федерация': 'RU',
    'србија': 'RS',
    'ўзбекистон республикаси': 'UZ',
    'қазақстан республикасы': 'KZ',
    'ҷумҳурии тоҷикистон': 'TJ',
    'հայաստանի հանրապետություն': 'AM',
    'இந்தியா': 'IN',
    'ราชอาณาจักรไทย': 'TH',
    'ሃገረ ኤርትራ': 'ER',
    'የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ': 'ET',
    '中华人民共和国': 'CN',
    '中華人民共和國澳門特別行政區': 'MO',
    '中華民國': 'TW',
    '新加坡共和国': 'SG',
    '남조선': 'KR',
    '북조선': 'KP',
    '조선민주주의인민공화국': 'KP',
}
DEMONYMS = {
    'afghan': 'AF',
    'albanian': 'AL',
    'algerian': 'DZ',
    'american': 'US',
    'american islander': 'UM',
    'american samoan': 'AS',
    'andorran': 'AD',
    'angolan': 'AO',
    'anguillian': 'AI',
    'antarctican': 'AQ',
    'antiguan': 'AG',
    'antiguan, barbudan': 'AG',
    'argentine': 'AR',
    'armenian': 'AM',
    'aruban': 'AW',
    'australian': 'AU',
    'austrian': 'AT',
    'azerbaijani': 'AZ',
    'bahamian': 'BS',
    'bahraini': 'BH',
    'bangladeshi': 'BD',
    'barbadian': 'BB',
    'barbudan': 'AG',
    'belarusian': 'BY',
    'belgian': 'BE',
    'belizean': 'BZ',
    'beninese': 'BJ',
    'bermudian': 'BM',
    'bhutanese': 'BT',
    'bolivian': 'BO',
    'bosnian': 'BA',
    'bosnian, herzegovinian': 'BA',
    'brazilian': 'BR',
    'british': 'GB',
    'bruneian': 'BN',
    'bulgarian': 'BG',
    'burkinabe': 'BF',
    'burmese': 'MM',
    'burundian': 'BI',
    'cambodian': 'KH',
    'cameroonian': 'CM',
    'canadian': 'CA',
    'cape verdian': 'CV',
    'caymanian': 'KY',
    'central african': 'CF',
    'chadian': 'TD',
    'channel islander': 'GG',
    'chilean': 'CL',
    'chinese': 'CN',
    'christmas islander': 'CX',
    'cocos islander': 'CC',
    'colombian': 'CO',
    'comoran': 'KM',
    'congolese': 'CD',
    'cook islander': 'CK',
    'costa rican': 'CR',
    'croatian': 'HR',
    'cuban': 'CU',
    'curaçaoan': 'CW',
    'cypriot': 'CY',
    'czech': 'CZ',
    'danish': 'DK',
    'djibouti': 'DJ',
    'dominican': 'DM',
    'dutch': 'NL',
    'east timorese': 'TL',
    'ecuadorean': 'EC',
    'egyptian': 'EG',
    'emirati': 'AE',
    'equatorial guinean': 'GQ',
    'eritrean': 'ER',
    'estonian': 'EE',
    'ethiopian': 'ET',
    'falkland islander': 'FK',
    'faroese': 'FO',
    'fijian': 'FJ',
    'filipino': 'PH',
    'finnish': 'FI',
    'french': 'FR',
    'french polynesian': 'PF',
    'gabonese': 'GA',
    'gambian': 'GM',
    'georgian': 'GE',
    'german': 'DE',
    'ghanaian': 'GH',
    'gibraltar': 'GI',
    'greek': 'GR',
    'greenlandic': 'GL',
    'grenadian': 'GD',
    'guadeloupian': 'GP',
    'guamanian': 'GU',
    'guatemalan': 'GT',
    'guianan': 'GF',
    'guinea-bissauan': 'GW',
    'guinean': 'GN',
    'guyanese': 'GY',
    'haitian': 'HT',
    'heard and mcdonald islander': 'HM',
    'herzegovinian': 'BA',
    'honduran': 'HN',
    'hong konger': 'HK',
    'hungarian': 'HU',
    'i-kiribati': 'KI',
    'icelander': 'IS',
    'indian': 'IN',
    'indonesian': 'ID',
    'iranian': 'IR',
    'iraqi': 'IQ',
    'irish': 'IE',
    'israeli': 'IL',
    'italian': 'IT',
    'ivorian': 'CI',
    'jamaican': 'JM',
    'japanese': 'JP',
    'jordanian': 'JO',
    'kazakhstani': 'KZ',
    'kenyan': 'KE',
    'kirghiz': 'KG',
    'kittitian': 'KN',
    'kittitian or nevisian': 'KN',
    'kosovar': 'XK',
    'kuwaiti': 'KW',
    'laotian': 'LA',
    'latvian': 'LV',
    'lebanese': 'LB',
    'liberian': 'LR',
    'libyan': 'LY',
    'liechtensteiner': 'LI',
    'lithuanian': 'LT',
    'luxembourger': 'LU',
    'macanese': 'MO',
    'macedonian': 'MK',
    'mahoran': 'YT',
    'malagasy': 'MG',
    'malawian': 'MW',
    'malaysian': 'MY',
    'maldivan': 'MV',
    'malian': 'ML',
    'maltese': 'MT',
    'manx': 'IM',
    'marshallese': 'MH',
    'martinican': 'MQ',
    'mauritanian': 'MR',
    'mauritian': 'MU',
    'mexican': 'MX',
    'micronesian': 'FM',
    'miquelonnais': 'PM',
    'moldovan': 'MD',
    'monegasque': 'MC',
    'mongolian': 'MN',
    'montenegrin': 'ME',
    'montserratian': 'MS',
    'moroccan': 'MA',
    'mosotho': 'LS',
    'motswana': 'BW',
    'mozambican': 'MZ',
    'namibian': 'NA',
    'nauruan': 'NR',
    'nepalese': 'NP',
    'nevisian': 'KN',
    'new caledonian': 'NC',
    'new zealander': 'NZ',
    'ni-vanuatu': 'VU',
    'nicaraguan': 'NI',
    'nigerian': 'NG',
    'nigerien': 'NE',
    'niuean': 'NU',
    'norfolk islander': 'NF',
    'north korean': 'KP',
    'norwegian': 'NO',
    'omani': 'OM',
    'pakistani': 'PK',
    'palauan': 'PW',
    'palestinian': 'PS',
    'panamanian': 'PA',
    'papua new guinean': 'PG',
    'paraguayan': 'PY',
    'peruvian': 'PE',
    'pitcairn islander': 'PN',
    'polish': 'PL',
    'portuguese': 'PT',
    'puerto rican': 'PR',
    'qatari': 'QA',
    'romanian': 'RO',
    'russian': 'RU',
    'rwandan': 'RW',
    'réunionese': 'RE',
    'sahrawi': 'EH',
    'saint barthélemy islander': 'BL',
    'saint helenian': 'SH',
    'saint lucian': 'LC',
    'saint martin islander': 'MF',
    'saint vincentian': 'VC',
    'saint-pierrais': 'PM',
    'saint-pierrais, miquelonnais': 'PM',
    'salvadoran': 'SV',
    'sammarinese': 'SM',
    'samoan': 'WS',
    'sao tomean': 'ST',
    'saudi arabian': 'SA',
    'senegalese': 'SN',
    'serbian': 'RS',
    'seychellois': 'SC',
    'sierra leonean': 'SL',
    'singaporean': 'SG',
    'slovak': 'SK',
    'slovene': 'SI',
    'solomon islander': 'SB',
    'somali': 'SO',
    'south african': 'ZA',
    'south georgian south sandwich islander': 'GS',
    'south korean': 'KR',
    'south sudanese': 'SS',
    'spanish': 'ES',
    'sri lankan': 'LK',
    'st. maartener': 'SX',
    'sudanese': 'SD',
    'surinamer': 'SR',
    'swazi': 'SZ',
    'swedish': 'SE',
    'swiss': 'CH',
    'syrian': 'SY',
    'tadzhik': 'TJ',
    'taiwanese': 'TW',
    'tanzanian': 'TZ',
    'thai': 'TH',
    'togolese': 'TG',
    'tokelauan': 'TK',
    'tongan': 'TO',
    'trinidadian': 'TT',
    'tunisian': 'TN',
    'turkish': 'TR',
    'turkmen': 'TM',
    'turks and caicos islander': 'TC',
    'tuvaluan': 'TV',
    'ugandan': 'UG',
    'ukrainian': 'UA',
    'uruguayan': 'UY',
    'uzbekistani': 'UZ',
    'vatican': 'VA',
    'venezuelan': 'VE',
    'vietnamese': 'VN',
    'virgin islander': 'VG',
    'wallis and futuna islander': 'WF',
    'yemeni': 'YE',
    'zambian': 'ZM',
    'zimbabwean': 'ZW',
    'ålandish': 'AX',
}
REGION_BY_ISO2 = {
    'AD': 'Europe',
    'AE': 'Asia',
    'AF': 'Asia',
    'AG': 'Americas',
    'AI': 'Americas',
    'AL': 'Europe',
    'AM': 'Asia',
    'AO': 'Africa',
    'AQ': 'Antarctic',
    'AR': 'Americas',
    'AS': 'Oceania',
    'AT': 'Europe',
    'AU': 'Oceania',
    'AW': 'Americas',
    'AX': 'Europe',
    'AZ': 'Asia',
    'BA': 'Europe',
    'BB': 'Americas',
    'BD': 'Asia',
    'BE': 'Europe',
    'BF': 'Africa',
    'BG': 'Europe',
    'BH': 'Asia',
    'BI': 'Africa',
    'BJ': 'Africa',
    'BL': 'Americas',
    'BM': 'Americas',
    'BN': 'Asia',
    'BO': 'Americas',
    'BQ': 'Americas',
    'BR': 'Americas',
    'BS': 'Americas',
    'BT': 'Asia',
    'BV': 'Antarctic',
    'BW': 'Africa',
    'BY': 'Europe',
    'BZ': 'Americas',
    'CA': 'Americas',
    'CC': 'Oceania',
    'CD': 'Africa',
    'CF': 'Africa',
    'CG': 'Africa',
    'CH': 'Europe',
    'CI': 'Africa',
    'CK': 'Oceania',
    'CL': 'Americas',
    'CM': 'Africa',
    'CN': 'Asia',
    'CO': 'Americas',
    'CR': 'Americas',
    'CU': 'Americas',
    'CV': 'Africa',
    'CW': 'Americas',
    'CX': 'Oceania',
    'CY': 'Europe',
    'CZ': 'Europe',
    'DE': 'Europe',
    'DJ': 'Africa',
    'DK': 'Europe',
    'DM': 'Americas',
    'DO': 'Americas',
    'DZ': 'Africa',
    'EC': 'Americas',
    'EE': 'Europe',
    'EG': 'Africa',
    'EH': 'Africa',
    'ER': 'Africa',
    'ES': 'Europe',
    'ET': 'Africa',
    'FI': 'Europe',
    'FJ': 'Oceania',
    'FK': 'Americas',
    'FM': 'Oceania',
    'FO': 'Europe',
    'FR': 'Europe',
    'GA': 'Africa',
    'GB': 'Europe',
    'GD': 'Americas',
    'GE': 'Asia',
    'GF': 'Americas',
    'GG': 'Europe',
    'GH': 'Africa',
    'GI': 'Europe',
    'GL': 'Americas',
    'GM': 'Africa',
    'GN': 'Africa',
    'GP': 'Americas',
    'GQ': 'Africa',
    'GR': 'Europe',
    'GS': 'Antarctic',
    'GT': 'Americas',
    'GU': 'Oceania',
    'GW': 'Africa',
    'GY': 'Americas',
    'HK': 'Asia',
    'HM': 'Antarctic',
    'HN': 'Americas',
    'HR': 'Europe',
    'HT': 'Americas',
    'HU': 'Europe',
    'ID': 'Asia',
    'IE': 'Europe',
    'IL': 'Asia',
    'IM': 'Europe',
    'IN': 'Asia',
    'IO': 'Africa',
    'IQ': 'Asia',
    'IR': 'Asia',
    'IS': 'Europe',
    'IT': 'Europe',
    'JE': 'Europe',
    'JM': 'Americas',
    'JO': 'Asia',
    'JP': 'Asia',
    'KE': 'Africa',
    'KG': 'Asia',
    'KH': 'Asia',
    'KI': 'Oceania',
    'KM': 'Africa',
    'KN': 'Americas',
    'KP': 'Asia',
    'KR': 'Asia',
    'KW': 'Asia',
    'KY': 'Americas',
    'KZ': 'Asia',
    'LA': 'Asia',
    'LB': 'Asia',
    'LC': 'Americas',
    'LI': 'Europe',
    'LK': 'Asia',
    'LR': 'Africa',
    'LS': 'Africa',
    'LT': 'Europe',
    'LU': 'Europe',
    'LV': 'Europe',
    'LY': 'Africa',
    'MA': 'Africa',
    'MC': 'Europe',
    'MD': 'Europe',
    'ME': 'Europe',
    'MF': 'Americas',
    'MG': 'Africa',
    'MH': 'Oceania',
    'MK': 'Europe',
    'ML': 'Africa',
    'MM': 'Asia',
    'MN': 'Asia',
    'MO': 'Asia',
    'MP': 'Oceania',
    'MQ': 'Americas',
    'MR': 'Africa',
    'MS': 'Americas',
    'MT': 'Europe',
    'MU': 'Africa',
    'MV': 'Asia',
    'MW': 'Africa',
    'MX': 'Americas',
    'MY': 'Asia',
    'MZ': 'Africa',
    'NA': 'Africa',
    'NC': 'Oceania',
    'NE': 'Africa',
    'NF': 'Oceania',
    'NG': 'Africa',
    'NI': 'Americas',
    'NL': 'Europe',
    'NO': 'Europe',
    'NP': 'Asia',
    'NR': 'Oceania',
    'NU': 'Oceania',
    'NZ': 'Oceania',
    'OM': 'Asia',
    'PA': 'Americas',
    'PE': 'Americas',
    'PF': 'Oceania',
    'PG': 'Oceania',
    'PH': 'Asia',
    'PK': 'Asia',
    'PL': 'Europe',
    'PM': 'Americas',
    'PN': 'Oceania',
    'PR': 'Americas',
    'PS': 'Asia',
    'PT': 'Europe',
    'PW': 'Oceania',
    'PY': 'Americas',
    'QA': 'Asia',
    'RE': 'Africa',
    'RO': 'Europe',
    'RS': 'Europe',
    'RU': 'Europe',
    'RW': 'Africa',
    'SA': 'Asia',
    'SB': 'Oceania',
    'SC': 'Africa',
    'SD': 'Africa',
    'SE': 'Europe',
    'SG': 'Asia',
    'SH': 'Africa',
    'SI': 'Europe',
    'SJ': 'Europe',
    'SK': 'Europe',
    'SL': 'Africa',
    'SM': 'Europe',
    'SN': 'Africa',
    'SO': 'Africa',
    'SR': 'Americas',
    'SS': 'Africa',
    'ST': 'Africa',
    'SV': 'Americas',
    'SX': 'Americas',
    'SY': 'Asia',
    'SZ': 'Africa',
    'TC': 'Americas',
    'TD': 'Africa',
    'TF': 'Antarctic',
    'TG': 'Africa',
    'TH': 'Asia',
    'TJ': 'Asia',
    'TK': 'Oceania',
    'TL': 'Asia',
    'TM': 'Asia',
    'TN': 'Africa',
    'TO': 'Oceania',
    'TR': 'Asia',
    'TT': 'Americas',
    'TV': 'Oceania',
    'TW': 'Asia',
    'TZ': 'Africa',
    'UA': 'Europe',
    'UG': 'Africa',
    'UM': 'Americas',
    'US': 'Americas',
    'UY': 'Americas',
    'UZ': 'Asia',
    'VA': 'Europe',
    'VC': 'Americas',
    'VE': 'Americas',
    'VG': 'Americas',
    'VI': 'Americas',
    'VN': 'Asia',
    'VU': 'Oceania',
    'WF': 'Oceania',
    'WS': 'Oceania',
    'XK': 'Europe',
    'YE': 'Asia',
    'YT': 'Africa',
    'ZA': 'Africa',
    'ZM': 'Africa',
    'ZW': 'Africa',
}


def region_for(destination: str) -> str | None:
    """Continent region ('Africa', 'Americas', 'Asia', 'Europe', 'Oceania',
    'Antarctic') for a free-text destination, via resolve_country(). Used by
    pricing.budget to pick a per-day eSIM data-cost tier — see REGION_SIM_RATES
    there. Returns None if the destination can't be resolved to a country.
    """
    code = resolve_country(destination)
    if not code:
        return None
    return REGION_BY_ISO2.get(code)
