# Generated by Django 6.1.1 on 2026-09-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('amadeus_flights', 'Amadeus — Flights'), ('amadeus_hotels', 'Amadeus — Hotels'), ('opentripmap', 'OpenTripMap — Attractions'), ('visa', 'Visa guidance'), ('exchange_rate', 'Exchange rate'), ('maps', 'Maps / transfer estimate')], max_length=32)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-called_at'],
            },
        ),
    ]
