# Generated by Django 6.1.1 on 2026-09-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationcalllog',
            name='provider',
            field=models.CharField(choices=[('amadeus_flights', 'Amadeus — Flights'), ('amadeus_hotels', 'Amadeus — Hotels'), ('opentripmap', 'OpenTripMap — Attractions'), ('visa', 'Visa guidance'), ('exchange_rate', 'Exchange rate'), ('maps', 'Maps / transfer estimate'), ('esim', 'eSIM Go — Data bundles')], max_length=32),
        ),
    ]
