# Generated by Django 6.1.1 on 2026-09-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_integrationcalllog_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationcalllog',
            name='provider',
            field=models.CharField(choices=[('travelpayouts', 'Travelpayouts — Flights'), ('opentripmap', 'OpenTripMap — Attractions (fallback)'), ('visa', 'Visa guidance'), ('exchange_rate', 'Exchange rate'), ('maps', 'Maps / transfer estimate'), ('esim', 'eSIM Go — Data bundles'), ('hotels', 'LiteAPI — Hotels'), ('hotels_stayapi', 'StayAPI — Hotels (tier 3)'), ('serpapi_flights', 'SerpApi — Flights (Google Flights, tier 1)'), ('serpapi_hotels', 'SerpApi — Hotels (Google Hotels, tier 1)'), ('serpapi_attractions', 'SerpApi — Attractions (Google Top Sights, tier 1)'), ('serpapi_search', 'SerpApi — Attraction link (gap-filler)')], max_length=32),
        ),
    ]
