# Generated by Django 6.1.1 on 2026-09-18 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.itinerary')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('time', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('cost_display', models.CharField(max_length=60)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trips.itineraryday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('nationality', models.CharField(max_length=80)),
                ('purpose', models.CharField(choices=[('Holiday', 'Holiday'), ('Business', 'Business'), ('Family Visit', 'Family Visit'), ('Honeymoon', 'Honeymoon')], default='Holiday', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('travel_style', models.CharField(choices=[('budget', 'Budget'), ('balanced', 'Comfortable / Balanced'), ('luxury', 'Luxury')], default='balanced', max_length=10)),
                ('hotel_preference', models.CharField(choices=[('3–4 Star Hotel', '3–4 Star Hotel'), ('Apartment', 'Apartment'), ('Resort', 'Resort'), ('Luxury Hotel', 'Luxury Hotel')], default='3–4 Star Hotel', max_length=30)),
                ('interests', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(choices=[('USD', 'USD ($)'), ('TZS', 'TZS'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)')], default='USD', max_length=3)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.JSONField(default=list, help_text='[{label, done}, ...]')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_trips', to=settings.AUTH_USER_MODEL)),
                ('trip_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_trip', to='trips.triprequest')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='trip_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='trips.triprequest'),
        ),
        migrations.CreateModel(
            name='BudgetBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(help_text='[{label, detail, amount}, ...]')),
                ('visa', models.JSONField(help_text='{type, method, stay, cost, tag}')),
                ('flights', models.JSONField(help_text='[{airline, route, stops, duration, price, label}, ...]')),
                ('hotels', models.JSONField(help_text='[{name, area, rating, night, total, desc}, ...]')),
                ('attractions', models.JSONField(help_text='[{name, cost, desc, optional}, ...]')),
                ('nights', models.PositiveSmallIntegerField()),
                ('people', models.PositiveSmallIntegerField()),
                ('flight_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attractions_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sim_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emergency_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('visa_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('over_budget', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_breakdown', to='trips.triprequest')),
            ],
        ),
    ]
