# Generated by Django 6.1.1 on 2026-09-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='hotel_preference',
            field=models.CharField(choices=[('3–4 Star Hotel', '★★★–★★★★ Hotel'), ('Apartment', 'Apartment'), ('Resort', '★★★★ Resort'), ('Luxury Hotel', '★★★★★ Luxury Hotel')], default='3–4 Star Hotel', max_length=30),
        ),
    ]
