# Generated by Django 6.1.1 on 2026-09-26 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_triprequest_hotel_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('city', models.CharField(max_length=120)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('hotel_preference', models.CharField(choices=[('3–4 Star Hotel', '★★★–★★★★ Hotel'), ('Apartment', 'Apartment'), ('Resort', '★★★★ Resort'), ('Luxury Hotel', '★★★★★ Luxury Hotel')], default='3–4 Star Hotel', max_length=30)),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='trips.triprequest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
