# Generated by Django 6.1.1 on 2026-09-26 13:03
"""Every TripRequest needs at least one TripLeg now that pricing.budget
reads legs, not the legacy destination/start_date/end_date fields, directly
— this backfills exactly one leg per existing trip from those legacy
fields, so nothing pre-dating multi-city support loses its plan.
"""
from django.db import migrations


def backfill_legs(apps, schema_editor):
    TripRequest = apps.get_model("trips", "TripRequest")
    TripLeg = apps.get_model("trips", "TripLeg")
    for trip_request in TripRequest.objects.filter(legs__isnull=True):
        TripLeg.objects.create(
            trip_request=trip_request,
            order=0,
            city=trip_request.destination,
            arrival_date=trip_request.start_date,
            departure_date=trip_request.end_date,
            hotel_preference=trip_request.hotel_preference,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_tripleg'),
    ]

    operations = [
        migrations.RunPython(backfill_legs, noop_reverse),
    ]
