# Generated by Django 6.1.1 on 2026-09-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_backfill_legs_for_existing_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetbreakdown',
            name='legs',
            field=models.JSONField(default=list, help_text='[{city, nights, hotels, attractions, hotel_cost, ...}, ...] — per-destination breakdown'),
        ),
    ]
