# Generated by Django 6.1.1 on 2026-09-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_budgetbreakdown_legs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='purpose',
            field=models.CharField(choices=[('Holiday', 'Holiday'), ('Business', 'Business'), ('Family Visit', 'Family Visit'), ('Honeymoon', 'Honeymoon'), ('Couple', 'Couple')], default='Holiday', max_length=20),
        ),
    ]
