# Generated by Django 6.1.1 on 2026-09-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_triprequest_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripleg',
            name='bed_configuration',
            field=models.CharField(choices=[('double', '1 Double/Queen Bed (Couple)'), ('king', '1 King Bed (Couple)'), ('twin', '2 Twin Beds'), ('family', 'Multiple Beds (Family)')], default='double', max_length=10),
        ),
        migrations.AddField(
            model_name='tripleg',
            name='rooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
