# Generated by Django 6.1.1 on 2026-09-29 12:25

from django.db import migrations, models

# The old choice set (room-style: "1 Double/Queen Bed", "2 Twin Beds", ...)
# is being replaced with standard mattress sizes. Real production TripLeg
# rows already exist under the old keys, so they're remapped here rather
# than left as stale values BED_CONFIGURATION_LABELS wouldn't recognize.
OLD_TO_NEW = {
    "double": "full",
    "twin": "single",
    "family": "full",
    # "king" is unchanged — present in both choice sets.
}


def remap_old_bed_configurations(apps, schema_editor):
    TripLeg = apps.get_model("trips", "TripLeg")
    for old, new in OLD_TO_NEW.items():
        TripLeg.objects.filter(bed_configuration=old).update(bed_configuration=new)


def remap_new_bed_configurations_back(apps, schema_editor):
    TripLeg = apps.get_model("trips", "TripLeg")
    TripLeg.objects.filter(bed_configuration="full").update(bed_configuration="double")
    TripLeg.objects.filter(bed_configuration="single").update(bed_configuration="twin")


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_tripleg_bed_configuration_tripleg_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripleg',
            name='bed_configuration',
            field=models.CharField(choices=[('single', 'Single / Twin'), ('twin_xl', 'Twin XL'), ('full', 'Double / Full'), ('queen', 'Queen'), ('king', 'King'), ('cal_king', 'California King')], default='queen', max_length=10),
        ),
        migrations.RunPython(remap_old_bed_configurations, remap_new_bed_configurations_back),
    ]
